#!/bin/bash

#########################################
# configuration
#########################################

PREFIX="$HOME/opt/cross"
TARGET=i686-elf

#########################################

if [ $# -ne 1 ]; then
    echo Usage:
    echo build-binutils \<binutils source path\>
    exit 1
fi

SRC_DIR=$(realpath $1)
BUILD_DIR=/tmp/build-binutils

# ensure build directory does not already exist
rm -rf $BUILD_DIR

# create new build directory
mkdir $BUILD_DIR
cd $BUILD_DIR

# build and install
$SRC_DIR/configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
make
make install

# remove build directory
rm -rf $BUILD_DIR
