#!/bin/bash

#########################################
# configuration
#########################################

PREFIX="$HOME/opt/cross"
TARGET=i686-elf

#########################################

if [ $# -ne 1 ]; then
    echo Usage:
    echo build-gcc \<gcc source path\>
    exit 1
fi

SRC_DIR=$(realpath $1)
BUILD_DIR=/tmp/build-gcc
export PATH="$PREFIX/bin:$PATH"

# get dependencies
CWD=$(pwd)
cd $SRC_DIR
./contrib/download_prerequisites
cd $CWD

# ensure build directory does not already exist
rm -rf $BUILD_DIR

# create new build directory
mkdir $BUILD_DIR
cd $BUILD_DIR

# build and install
$SRC_DIR/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c,c++ --without-headers
make all-gcc
make all-target-libgcc
make install-gcc
make install-target-libgcc

# remove build directory
rm -rf $BUILD_DIR
